In [9]:
%reload_ext autoreload
%autoreload

import simulation.gas_drift as gd
import visualization.array_rendering as ar
import numpy as np

test_carbon_dioxide = np.array(
    [[0, 0, 0],
    [0, 1, 0],
    [0, 0, 0]]
)

test_matrix = np.array(
    [[1, 2, 0],
    [0, 1, 1],
    [0, 1, 1]]
)



print(test_matrix)
print(test_carbon_dioxide)
print(test_matrix * test_carbon_dioxide)
print(test_carbon_dioxide * test_matrix)

[[1 2 0]
 [0 1 1]
 [0 1 1]]
[[0 0 0]
 [0 1 0]
 [0 0 0]]
[[0 0 0]
 [0 1 0]
 [0 0 0]]
[[0 0 0]
 [0 1 0]
 [0 0 0]]
